//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventHubEntities : DbContext
    {
        public EventHubEntities()
            : base("name=EventHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Divulgacao> Divulgacaos { get; set; }
        public virtual DbSet<EnderecoEvento> EnderecoEventoes { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<InscritosEvento> InscritosEventoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
