//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divulgacao
    {
        public string Descricao { get; set; }
        public string Title { get; set; }
        public string Fonte { get; set; }
        public string Id { get; set; }
        public string DataAlteração { get; set; }
        public string Texto { get; set; }
        public Nullable<int> IdTweet { get; set; }
        public Nullable<int> IdAgenda { get; set; }
        public Nullable<int> IdEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
