//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnderecoEvento
    {
        public string Cidade { get; set; }
        public string Logradouro { get; set; }
        public string Bairro { get; set; }
        public string Estado { get; set; }
        public string Id { get; set; }
        public string Complemento { get; set; }
        public string CEP { get; set; }
        public string Número { get; set; }
        public Nullable<int> IdEvento { get; set; }
    
        public virtual Eventos Eventos { get; set; }
    }
}
