//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub.Domain
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventHubEntities : DbContext
    {
        public EventHubEntities()
            : base("name=EventHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventSubscribers> EventSubscribers { get; set; }
        public virtual DbSet<GoogleCalendarSocialMarketing> GoogleCalendarSocialMarketing { get; set; }
        public virtual DbSet<PublicPlace> PublicPlace { get; set; }
        public virtual DbSet<TwitterSocialMarketing> TwitterSocialMarketing { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
